inherit_from: ./configs/ScanNet/scannet_mono.yaml
mode: mono
mapping:
  device: "cuda:0"
  bound: [[-10.0, 10.0], [-6.0, 9.0], [-10.0, 7.0]] 

# meshing:
  # gt_mesh_path: '/home/yzhang/data/ScanNet/scans/scene0000_00/scene0000_00_vh_clean.ply'

data:
  input_folder: dataset/stomach/TumorfreeTrajectory_1
  output: exps/goslam/scannet/0000/mono
